import DrinkTable from "@/components/drinks/DrinkTable";

<<<<<<< HEAD
import Users from "./Users/page";
=======
import Users from "./users/page";
>>>>>>> 174f0fe82835bae5c49874e9c547b2b7cb50043a
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// import './globals.css'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <Users/>
        <DrinkTable/>

      </body>
    </html>
  );
}
