import DrinkTable from "@/components/drinks/DrinkTable";

import Users from "./users/page";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import './globals.css'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
<<<<<<< HEAD
        <Users/>
        <DrinkTable/>
=======

        <Users/>
        <DrinkTable/>
       {/* <UserPage/>
        <DrinkTable/> */}
>>>>>>> 77ac2305194137c1a9d4e369c1170bcc2e21d84d

      </body>
    </html>
  );
}
